name: Mi primer workflow

on: [push]  # Se ejecutará cuando hagas un "push"

jobs:
  say_hello:
    runs-on: ubuntu-latest  # Elige el sistema operativo donde se ejecutará

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2  # Descarga el código del repo

      - name: Run Build Script
        run: echo "¡Hola desde GitHub Actions!"
